# #ARG PYTHON_VERSION="3.8.6"
# #FROM python:${PYTHON_VERSION}-slim-buster

# FROM fastai/fastai:latest
# WORKDIR /app

# COPY . /app

# RUN pip install -r requirements.txt

# EXPOSE 5000

# CMD ["python","./api.py"]
FROM fastai/fastai:latest
WORKDIR /app

# COPY . /app
COPY requirements.txt requirements.txt
RUN --mount=type=cache,target=/root/.cache pip install -r requirements.txt

EXPOSE 5000

CMD ["python","./api.py"]