module.exports = {
    hello: "Xin chào, mình là TMT Intelligent Chatbot. Bạn cần mình giúp gì nè (viết đầy đủ tiếng việt có dấu giúp mình)",
    err: "Có lỗi xảy ra, bạn vui lòng F5 lại trang giúp mình nhé!",
    cantfind: "Không tìm được thủ tục thỏa các yêu cầu, hãy nhập chính xác yêu cầu tên thủ tục",
    thank: "Cảm ơn bạn. Chúc bạn có một ngày vui vẻ!",
    whatyourattr: "Yêu cầu của bạn là gì?",
    showall: "Bạn có muốn xem thêm kết quả không?",
    dontunderstand: "Tôi không hiểu ý của bạn lắm. Xin hãy nhập lại.",
    reset: 'Hãy nhập thông tin bạn cần nhé',
    diadiem: ['Làm thủ tục này tại:','Bạn có thể đến'],
    nochiphi: 'Thủ tục này không cần chi phí nào',
    chiphi: ['Thủ tục này gồm các lệ phí sau: ','Bạn cần chuẩn bị lệ phí cho: '],
    thoigian: 'Thời gian làm thủ tục này là: ',
    True: 'True',
    False: 'False',
    cs: 'Câu này hỏi về màu sắc và size',
    c: "Câu này hỏi về màu sắc",
    s: "Câu này hỏi về size",
    n: "Không hỏi về màu sắc và size",
    transfer_to_admin: "Rất xin lỗi vì không giúp gì được cho bạn",
    found_id_product: "Bạn muốn mua ... ",
    not_found_product: "Xin lỗi quý khách shop đã hết hàng rồi ạ. Anh chị muốn mua sản phẩm khác không ạ ?",
    not_found_product_image: "Xin lỗi quý khách. Hiện hệ thống đang gặp sự cố do quá tải. Chúng tôi sẽ cố gắng khắc phục lỗi này trong thời gian sớm nhất",
    found_lots_products:"Quý khách muốn đặt",
    rep_hello: "Shop chào bạn ạ",
    rep_done: "Chân thành cảm ơn quý khách đã tin tưởng đặt hàng tại shop",
    rep_inform: "Shop xin chốt lại đơn hàng của mình nhé: ",
    rep_request: "Shop chào bạn ạ request",
    rep_feedback: "Shop chào bạn ạ feedback",
    rep_connect: "Shop chào bạn ạ connect",
    rep_order: "Cảm ơn quý khách",
    rep_order_color: "Hiện shop đang có một số  sản phẩm cùng loại đó nè. Anh chị muốn lấy màu gì ạ ?",
    rep_order_size: "Anh chị lấy size gì đây ạ ?",
    rep_order_product_name: "Anh chị muốn lấy sản phẩm nào vậy ạ?",
    rep_order_amount: "Anh chị lấy số lượng bao nhiêu ạ ?",
    rep_changing: "Shop chào bạn ạ changing",
    rep_return: "Shop chào bạn ạ return",
    have_product_name: "Dạ, bên shop vẫn còn hàng nhé anh chị.",
    dont_reg_color: "Xin lỗi, shop chưa hiểu ý anh chị ạ. Anh chị cần màu gì ?",
    misunderstand_color: "Anh chị chốt lại là màu nào giúp shop với ạ ?",
    misunderstand_size: "Anh chị chốt lại là size nào giúp shop với ạ ?",
    misunderstand_amount: "Anh chị chốt lại số lượng giúp shop với ạ ?",
    misunderstand_product_name: "Anh chị chốt lại sản phẩm mình muốn đặt giúp shop với ạ ?",
}